name: Publish Snapshot to Maven Central

on:
  push:
    tags: [ 'v*-SNAPSHOT' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Publish snapshot to Central Portal
        run: ./gradlew clean publishMavenJavaPublicationToCentralSnapshotsRepository
        env:
          MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
